---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctp-deployment
spec:
  selector:
    matchLabels:
      app: sctp
  replicas: 1
  template:
    metadata:
      labels:
        app: sctp
    spec:
      containers:
        - name: sctp
          image: aweimeow/sctp-server
          command: ["bash", "-xc"]
          args:
            - python example/run.py
          ports:
            - name: sctp
              containerPort: 9999
              protocol: SCTP
